import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const categorizedMenuItems = [
  {
    id: "home",
    title: "Ana Sayfa",
    path: "/",
    type: "link",
  },
  {
    id: "ai-components",
    title: "AI Bileşenleri",
    type: "menu",
    children: [
      {
        id: "ai-based-conversational-practice",
        title: "AI Konuşma Pratiği",
        path: "/components-pages/ai-based-conversational-practice",
        type: "link",
      },
      {
        id: "listening-and-speaking",
        title: "Dinleme ve Konuşma",
        path: "/components-pages/listening-and-speaking",
        type: "link",
      },
    ],
  },
  {
    id: "question-types",
    title: "Soru Tipleri",
    type: "menu",
    children: [
      {
        id: "multiple-choice-questions",
        title: "Çoktan Seçmeli",
        path: "/components-pages/multiple-choice-questions",
        type: "link",
      },
      {
        id: "visual-multiple-choice-questions",
        title: "Görsel Çoktan Seçmeli",
        path: "/components-pages/visual-multiple-choice-questions",
        type: "link",
      },
      {
        id: "listening-questions",
        title: "Dinleme Soruları",
        path: "/components-pages/listening-questions",
        type: "link",
      },
      {
        id: "long-text-questions",
        title: "Uzun Metin Soruları",
        path: "/components-pages/long-text-questions",
        type: "link",
      },
      {
        id: "fill-in-the-blanks",
        title: "Boşluk Doldurma",
        path: "/components-pages/fill-in-the-blanks",
        type: "link",
      },
      {
        id: "speaking-questions",
        title: "Konuşma Soruları",
        path: "/components-pages/speaking-questions",
        type: "link",
      },
    ],
  },
  {
    id: "interactive",
    title: "Etkileşimli",
    type: "menu",
    children: [
      {
        id: "interactive-games",
        title: "Etkileşimli Oyunlar",
        path: "/components-pages/interactive-games",
        type: "link",
      },
      {
        id: "role-playing-games",
        title: "Rol Yapma Oyunları",
        path: "/components-pages/role-playing-games",
        type: "link",
      },
    ],
  },
  {
    id: "content",
    title: "İçerik",
    type: "menu",
    children: [
      {
        id: "video-content",
        title: "Video İçerik",
        path: "/components-pages/video-content",
        type: "link",
      },
      {
        id: "vocabulary-knowledge",
        title: "Kelime Bilgisi",
        path: "/components-pages/vocabulary-knowledge",
        type: "link",
      },
      {
        id: "word-or-sentence-formation",
        title: "Kelime/Cümle Oluşturma",
        path: "/components-pages/word-or-sentence-formation",
        type: "link",
      },
    ],
  },
];

const imageLogo = {
  type: "image",
  src: "/logo.png",
  alt: "Logo",
  width: 150,
  height: 50,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header menuItems={categorizedMenuItems} logo={imageLogo} />
        {children}
      </body>
    </html>
  );
}
